# Generated by Django 5.2.9 on 2025-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fmsuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='fmsuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fmsuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver'), ('guest', 'Guest')], default='guest', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='fmsuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='fmsuser',
            table=None,
        ),
    ]
