# Generated by Django 5.2.9 on 2025-12-05 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_fmsuser_options_remove_fmsuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fmsuser',
            options={'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
        migrations.AddField(
            model_name='fmsuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='fmsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='fmsuser',
            table='system_users',
        ),
    ]
