# Generated by Django 5.2.9 on 2025-12-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fmsuser_options_fmsuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmsuser',
            name='username',
        ),
    ]
