# Generated by Django 5.2.9 on 2025-12-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fmsuser_first_name_alter_fmsuser_last_login_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmsuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='system_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='fmsuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='system_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
