# Generated by Django 5.2.9 on 2025-12-04 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_code', models.CharField(max_length=50, unique=True)),
                ('scheduled_start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescue', 'Rescue'), ('Backload', 'Backload')], default='Scheduled', max_length=50)),
                ('load_type', models.CharField(choices=[('Dry', 'Dry'), ('Chilled', 'Chilled'), ('Ref', 'Ref'), ('Combi', 'Combi')], default='Dry', max_length=50)),
                ('loading_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='customers.customer')),
                ('destination_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_trips', to='locations.location')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to='employees.employee')),
                ('helper1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_trips_1', to='employees.employee')),
                ('helper2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_trips_2', to='employees.employee')),
                ('origin_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_trips', to='locations.location')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trucks.truck')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Loading_Arrival', 'Loading Arrival'), ('Loading_Start', 'Loading Start'), ('Unloading_Finish', 'Unloading Finish')], max_length=50)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('encoder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_events', to='employees.employee')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Event',
                'verbose_name_plural': 'Trip Events',
                'db_table': 'trip_events',
            },
        ),
        migrations.CreateModel(
            name='TripFuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('encoder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_fuels', to='employees.employee')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Fuel',
                'verbose_name_plural': 'Trip Fuels',
                'db_table': 'trip_fuels',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='idx_trips_status'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['scheduled_start_time'], name='idx_trips_scheduled_date'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['customer'], name='idx_trips_customer'),
        ),
    ]
