# Generated by Django 5.2.9 on 2025-12-05 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripevent',
            name='encoder',
        ),
        migrations.RemoveField(
            model_name='tripevent',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripfuel',
            name='encoder',
        ),
        migrations.RemoveField(
            model_name='tripfuel',
            name='trip',
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='idx_trips_status',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='idx_trips_scheduled_date',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='idx_trips_customer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='helper1',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='helper2',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='load_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='loading_ref_no',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='assigned_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
        migrations.DeleteModel(
            name='TripEvent',
        ),
        migrations.DeleteModel(
            name='TripFuel',
        ),
    ]
