# Generated by Django 5.2.9 on 2025-12-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_tripevent_encoder_remove_tripevent_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_code',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
