# Generated by Django 5.2.9 on 2025-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_trip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
