# Generated by Django 5.2.9 on 2025-12-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_idx_trucks_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='truck',
            name='idx_trucks_status',
        ),
    ]
