# Generated by Django 5.2.9 on 2025-12-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_remove_truck_idx_trucks_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['status'], name='idx_trucks_status'),
        ),
    ]
